/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AgeRatioChart: typeof import('./../views/screen/components/AgeRatioChart.vue')['default']
    AnnualVisitorsChart: typeof import('./../views/screen/components/AnnualVisitorsChart.vue')['default']
    BookingChannelsChart: typeof import('./../views/screen/components/BookingChannelsChart.vue')['default']
    Category: typeof import('./../components/Category/index.vue')['default']
    Dialog: typeof import('./../myComponents/dialog/index.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCascader: typeof import('element-plus/es')['ElCascader']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    Future30VisitorsChart: typeof import('./../views/screen/components/Future30VisitorsChart.vue')['default']
    HotSceneryAreasChart: typeof import('./../views/screen/components/HotSceneryAreasChart.vue')['default']
    IForm: typeof import('./../myComponents/IForm/index.vue')['default']
    ILayout: typeof import('./../myComponents/ILayout/index.vue')['default']
    Loading: typeof import('./../components/Loading/index.vue')['default']
    MapAirplaneRoutesChart: typeof import('./../views/screen/components/MapAirplaneRoutesChart.vue')['default']
    My: typeof import('./../myComponents/my.vue')['default']
    RealTimeVisitorChart: typeof import('./../views/screen/components/RealTimeVisitorChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./../myComponents/search/index.vue')['default']
    SexRatioChart: typeof import('./../views/screen/components/SexRatioChart.vue')['default']
    SkuForm: typeof import('./../views/product/spu/components/SkuForm.vue')['default']
    SpuForm: typeof import('./../views/product/spu/components/SpuForm.vue')['default']
    SvgIcon: typeof import('./../components/SvgIcon/index.vue')['default']
    Table: typeof import('./../myComponents/table/index.vue')['default']
  }
}
